### ISSUE TITLE
API

### ISSUE THREAD

**Issue by ThanhPham1987** [ben-omji/serve_yolov5#2]
Hi @ben-omji ,
When i run  ./run_ts.sh coco_yolov5s.mar. And after that on the browser, I type localhost:9080. I have issue like image belows:
 
![Screenshot from 2023-07-31 21-44-25](https://github.com/ben-omji/serve_yolov5/assets/22832922/43f47e9a-3982-4c59-9484-5a4dedfcf0eb)

Best regards,
PeterPham

**Comment by ben-omji** [comment]
Hello again @ThanhPham1987,

Typing the URI to a browser means making a request of 'GET' method for the URI.
You should make a request of other proper method for the URI. (README shows you making 'PUT' request using curl)

And you can refer this [page](https://pytorch.org/serve/inference_api.html) for API examples.

I will close the issue #1 because it looks like you are on the next step.

**Comment by ThanhPham1987** [comment]
> Hello again @ThanhPham1987,
> 
> Typing the URI to a browser means making a request of 'GET' method for the URI. You should make a request of other proper method for the URI. (README shows you making 'PUT' request using curl)
> 
> And you can refer this [page](https://pytorch.org/serve/inference_api.html) for API examples.
> 
> I will close the issue #1 because it looks like you are on the next step.



> 

Thanks
